name: kisiselfinansapp
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.3
  cloud_firestore: ^5.6.7
  google_sign_in: ^6.3.0
  provider: ^6.1.4 
  cupertino_icons: ^1.0.8
  async: ^2.12.0
  fake_async: ^1.3.2
  leak_tracker: ^10.0.8
  material_color_utilities: ^0.11.1
  vm_service: ^14.3.1
  fluttertoast: ^8.2.8
  pie_chart: ^5.4.0 
  fl_chart: ^0.71.0
  intl: 0.17.0
  google_mlkit_text_recognition: ^0.15.0
  image_picker: ^1.0.4
  path_provider: ^2.1.2
  js: ^0.7.2
  charts_flutter: ^0.12.0



  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/spendwise_logo.png
    - assets/images/google_logo.png
    - assets/images/income_expenses_icon.png
    - assets/images/budget_planning_icon.png
    - assets/images/smart_spending_icon.png
    - assets/images/receipt_ocr_icon.png
    - assets/images/subscription_tracking_icon.png
    - assets/images/financial_goals_icon.png
    - assets/images/data_visualization_icon.png
