// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDr81xEalGQdMhclFp5l6D8TiYgT7NQSqI',
    appId: '1:52183883036:web:8f192f433e06e51cc9eed9',
    messagingSenderId: '52183883036',
    projectId: 'kisiselfinansapp',
    authDomain: 'kisiselfinansapp.firebaseapp.com',
    storageBucket: 'kisiselfinansapp.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIIKdUqh6JHm1FVEy70xfN9iG10FoB1WQ',
    appId: '1:52183883036:android:77c44bbe233e6b39c9eed9',
    messagingSenderId: '52183883036',
    projectId: 'kisiselfinansapp',
    storageBucket: 'kisiselfinansapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSNmmCAbh9FbcFNzOpu4kvJRKX0oaIp2g',
    appId: '1:52183883036:ios:176ec0387416ab2cc9eed9',
    messagingSenderId: '52183883036',
    projectId: 'kisiselfinansapp',
    storageBucket: 'kisiselfinansapp.firebasestorage.app',
    iosBundleId: 'com.example.kisiselfinansapp',
  );

}